site_name: Keybot 5716
copyright: © Copyright 2025, Keybot 5716
site_author: Equipo de programación :) (Fundador de página: Lider de programación 2021 - 2023 UwU)
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - c++
    - cpp
    - java
  logo: 'logo.png'
  locale: es

nav:
  - 'Bienvenida':
    - Inicio: 'index.rst'
    - Acerca de nosotrx: 'Acerca.rst'
  - 'Areas de Ingenieria':
    - 'Programación':
      - Inicio: 'Programación/Inicio.rst'
      - Links Utiles: 'Programación/Links.rst'
      - Codigos Pasados: 'Programación/Codigos.rst'  
      - Configuración de Entorno: 'Programación/Configuracion.rst'  
      - Recursos Tecnicos: 'Programación/Recursos.rst'  
      - Estandares de programación: 'Programación/Estandares.rst'  
    - Electronica: 'Electronica/Inicio.rst'
    - Mecanica: 'Mecanica/Inicio.rst'
