site_name: Keybot 5716
copyright: © Copyright 2025, Keybot 5716
site_author: Equipo de programación Fundador de página Lider de programación 2021 - 2023 UwU)
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - c++
    - cpp
    - java
  logo: 'logo.png'
  locale: es

nav:
  - Inicio: 'index.md'
  - 'Bienvenida':
    - Inicio: 'index.md'
    - Acerca de nosotrx: 'Acerca.md'
  - 'Areas de Ingenieria':
    - 'Programación':
      - Inicio: 'Programación/Inicio.md'
      - Links Utiles: 'Programación/Links.md'
      - Codigos Pasados: 'Programación/Codigos.md'  
      - Configuración de Entorno: 'Programación/Configuracion.md'  
      - Recursos Tecnicos: 'Programación/Recursos.md'  
      - Estandares de programación: 'Programación/Estandares.md'  
    - Electronica: 'Electronica/Inicio.md'
    - Mecanica: 'Mecanica/Inicio.md'
